workflows:
  android-release:
    name: BB Keyboard APK
    max_build_duration: 20
    instance_type: mac_mini_m2
    environment:
      flutter: stable
    scripts:
      - name: Build APK
        script: flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/*.apk